isPartial: False
partialexpname: dvmatcher_scape_partial

expname: dvmatcher_scape_r

dataset: scape_r

deform_mesh: False

loss:
  k_deform: 10
  
# misc
misc:
  cuda: True
  device: 0
  checkpoint_interval: 1
  log_interval: 5000
